language: node_js
node_js:
  - "0.11"
  - "0.10"
notifications:
  email: false
install: npm install
script: CODECLIMATE_REPO_TOKEN=094212d256c7224bdd97c0cd8e3f8de232d2512cf0184670abef7e475ca10d93 ./script/test
